### ISSUE TITLE
Activation layer should be handled as a independent layer

### ISSUE THREAD

**Issue by ZongHong-Lyu** [DigitalMediaProfessionals/tool#30]
After further investigate NASNet in #4, it has some divergence paths where one path applies activation for the output and another does not.

Currently the tool automatically merges activation layer with convolution layer, so for this kinds of model it either will apply activation to both path or the activation layer will be lost.

It should be fixed so that the activation layers are treated as independent layer, and only merge with convolution layer when converting to FPGA configs.

**Comment by YuyaKobayashi** [comment]
Same as fot BatchNormalization
