### ISSUE TITLE
Failed to convert pure Dense network.

### ISSUE THREAD

**Issue by nhatuan84** [DigitalMediaProfessionals/tool#75]
Hi,

I faced the error when converting pure Dense network.
The model:
`	model = Sequential()
	model.add(Dense(100, input_dim = 6, kernel_initializer = 'normal', activation = 'relu'))
	model.add(Dense(100, kernel_initializer = 'normal', activation = 'relu'))
	model.add(Dense(100, kernel_initializer = 'normal', activation = 'relu'))
	model.add(Dense(1, kernel_initializer = 'normal'))`

The h5 is here:
https://drive.google.com/file/d/1mosKiCyzkmbGDT7-UaChOm7IEbyWNVmi/view?usp=sharing

Best regards

**Comment by ZongHong-Lyu** [comment]
Hi Tuan,

I've fixed it in the newest commit. It works for the model constructed in your comment.
But in your attached model, there are also Lamda layers, which is not possible to support in tool now.
Do you need Lamba support or only dense only support?

**Comment by nhatuan84** [comment]
Hi Lyu,

I did not use any Lamda layers. Maybe some funstions from Keras use it behind. I will check it. 

Thanks.

**Comment by ZongHong-Lyu** [comment]
Hi Tuan,

If now you can success convert network, please close this issue.

**Comment by nhatuan84** [comment]
Hi Lyu,

It was fixed. Thanks.
